### ISSUE TITLE
Adjusting dependencies to JupySQL

### ISSUE THREAD

**Issue by idomic** [usdoj-crt/crt-portal#1376] opened 2023-04-07 20:07 UTC
I think it'll be beneficial for you to use [Jupysql](https://github.com/ploomber/jupysql) in your repo as we've added support in many interactive features on top of `ipython-sql`. There's backward compatibility so it's just changing the dependency.

**Comment by okkays** [comment] 2023-04-11 15:49
Hi - this is a duplicate of the pull you'd opened previously. Can you help me get answers to the questions from https://github.com/usdoj-crt/crt-portal/pull/1346?

> I'm having trouble verifying your fork as the new "official" solution - can you help me out?
> 
> - ipython-sql has been a well-maintained standard for over a decade now. Can you provide documentation where they officially have discontinued support?
> - I don't see where the owner of ipython-sql has made an official handoff to your team - can you help me find that?

Closing in the meantime - feel free to reopen if you can help us get answers to the above.

Good luck with your project!

**Comment by okkays** [comment] 2023-04-24 14:52
Reopening per https://github.com/usdoj-crt/crt-portal/pull/1346

**Comment by okkays** [comment] 2023-06-12 20:12
Done - the most recent uses jupysql now - thanks for taking over that work!

**Closed by okkays** 2023-06-12 20:12 UTC
